### PR TITLE
Fix broken Operators url

### PR DESCRIPTION
**Pull request by ErnestoSerranoHA**
The Operators url seems to have changed to https://docs.mulesoft.com/dataweave/latest/dw-operators

### CODE REVIEW

**Comment by uip-robot-zz** [comment]
Git2Gus App is installed but the `.git2gus/config.json` doesn't exist.

**Comment by afelisatti** [comment]
Thanks, @ErnestoSerranoHA !! We missed this. Could you sign the contributor's agreement as required above?

**Comment by ErnestoSerranoHA** [comment]
Contributor License Agreement signed.

**Review by afelisatti — APPROVED** [review]

**Comment by afelisatti** [comment]
Sorry, @ErnestoSerranoHA, could you try that again? Your user is not showing up as having signed.

**Pull request merged**
