### PR TITLE
Fix typo in filterObject description

### PR DESCRIPTION
**Pull request by ghost**
This is probably a typo. This fix makes it more clear that filter & filterObject do not just move items around, but the items are actually removed instead.

### CODE REVIEW

**Review by teofr — APPROVED** [review]

**Comment by teofr** [comment]
Thanks @ideliakos please remember to sign the Contributor License Agreement so we can merge this PR

**Comment by ghost** [comment]
> Thanks @ideliakos please remember to sign the Contributor License Agreement so we can merge this PR

Hi @teofr, there seems to be a problem during the signing of the CLA. That may be the same reason why the other PR is still open. Not sure how to get around it... The 1st time I tried to do it, I got an error message even though Github authentication was successful and the checkboxes were checked. Every time I click on it and try to repeat the process since then, it ends up displaying this:
image

**Comment by teofr** [comment]
Thanks @ideliakos let me check if we can do anything on our side.

**Comment by teofr** [comment]
Thanks @ideliakos we were able to rerun the bot and merge the PR?

**Pull request merged**
